### ISSUE TITLE
No error messages created when a tablature contains unsupported characters

### ISSUE THREAD

**Issue by tuansydau** [Stan15/TAB2XML#17]
**Product**: Tab2XML
**Operating System**: Windows 10
**Opened with**: MuseScore (MuseScore)
**Priority**: minor

**Description**: When converting an invalid guitar tab, there is no error message that describes the problem to the user.

**Steps to Reproduce Error**:

1. Start the project using Gradle > Run.
2. Enter a valid guitar tab either by copying and pasting the tablature into the text area, or by uploading a file with the File > Open feature.
3. In any given line, enter a string of random and unsupported characters. An example is shown in the screenshot at the end of the issue.

**Expected Behaviour**: The program should show the user an error message stating that there are unsupported characters in the tab so that the user knows how to fix the tablature.

**Actual Behaviour**: No error message is displayed, and the entire measure with the invalid characters is highlighted.

**Screenshots**:
![image](https://user-images.githubusercontent.com/26176104/112407615-c75f1580-8cec-11eb-9e95-fbc714479134.png)

**Comment by Stan15** [comment]
Hi. Thanks for your big report. Input on our program is highly valued. 

I just wanted to point out that the error doesn't display because there is an error taking greater precedence. 

If you hover your mouse over the highlight, you would see that the program tells you it expects the number of characters in each measure line of the measure to be the same. 

When you fix that error, it will then show you another error, notifying you of unsupported characters.
