### ISSUE TITLE
Blank guitar tab output for some tabs but not others

### ISSUE THREAD

**Issue by Hartley-Madison-215062417** [Stan15/TAB2XML#23]
Title: blank guitar tab output for some tabs but not others

Reported By:
Madison hartley

Version:
Commit: e2614e6

Platform:
Windows 10
Java 15
Eclipse 4.18

Reproduction:

Start up software. Input the text from this file into the textbox:
[creep.txt](https://github.com/Stan15/TAB2XML/files/6201738/creep.txt)
And then convert. Follow onscreen steps, then open the .xml file.
Open. See how there is an output.

Now convert the next one. Copy the test from this file into the textbox:
[AllAlongTheWatchtower.txt](https://github.com/Stan15/TAB2XML/files/6201761/AllAlongTheWatchtower.txt)
And follow the steps to convert again. Open the converted file. See that it is empty.

Expected:
Either a converted tab, or, an error message indicating that the conversion failed and why it failed so the tab can be fixed.

Actual:
No error message, and blank .xml file saved.

Priority:
Low

Severity:
Low

Screenshots:

![zfgdshhh](https://user-images.githubusercontent.com/46429357/112412822-85869d00-8cf5-11eb-8d76-1a80e47ad059.PNG)

**Comment by Stan15** [comment]
Thank you for notifying us of this issue. It has been fixed in the latest version of the software. You are no longer able to convert unless there is a recognized measure present in the text field (even if it is valid, as long as there is no grey highlight on the measure- i.e it is recognized- the convert button will be enabled)
